### ISSUE TITLE
3.5 字体Icon: 在 pubspec.yaml 中自定义图标字体 family 的名字是不是要以大写开头?

### ISSUE THREAD

**Issue by jhwsx** [flutterchina/flutter-in-action#395]
```
fonts:
  - family: myIcon  #指定一个字体名
    fonts:
      - asset: fonts/iconfont.ttf
```
测试发现, 使用 `myIcon` 无法加载出图标字体, 改用 `MyIcon` 后加载成功.
